  CREATE TABLE PNY_MD_UPLOAD_FILE_FORMAT
(
	UPLOAD_FORMAT_ID NUMBER NOT NULL,
	UPLOAD_TYPE_CODE CHARACTER VARYING(50),
	UPLOAD_DESC	CHARACTER VARYING(100),
	DESTINATION_TABLE CHARACTER VARYING(50),
	DELIMITER_CHAR CHARACTER VARYING(5)
	FILE_PREFIX	CHARACTER VARYING(30)
	FILE_LOCATION CHARACTER VARYING(200)
	FILE_EXTENSION CHARACTER VARYING(30)
	RECORD_STATUS CHARACTER VARYING(1)
	CREATED_BY CHARACTER VARYING(50) DEFAULT 'SYSTEM'::CHARACTER VARYING,
	CREATED_ON TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
	MODIFIED_BY	CHARACTER VARYING(50) DEFAULT 'SYSTEM'::CHARACTER VARYING,
	MODIFIED_ON	TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
  CONSTRAINT PNY_MD_UPLOAD_FILE_FORMAT_PKEY PRIMARY KEY (UPLOAD_FORMAT_ID),
  CONSTRAINT PNY_MD_UPLOAD_FILE_FORMAT_UNIQUE_UPLOAD_TYPE_CODE UNIQUE (UPLOAD_TYPE_CODE)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE PNY_MD_UPLOAD_FILE_FORMAT
  OWNER TO apps_system;


CREATE SEQUENCE PNY_MD_UPLOAD_FILE_FORMAT_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 20;
ALTER TABLE PNY_MD_UPLOAD_FILE_FORMAT_SEQ
  OWNER TO apps_system;
  

