  CREATE TABLE PNY_MD_BRANCH
(
  BRANCH_ID	NUMBER NOT NULL,
  BRANCH_CODE	CHARACTER VARYING(2),
  BRANCH_NAME	CHARACTER VARYING(50),
  RECORD_STATUS CHARACTER VARYING(1),
  CREATOR_ID CHARACTER VARYING(20) DEFAULT 'SYSTEM'::CHARACTER VARYING,
  CREATED_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
  LAST_USER_ID CHARACTER VARYING(20) DEFAULT 'SYSTEM'::CHARACTER VARYING,
  LAST_UPDATE TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
  CONSTRAINT PNY_MD_BRANCH_PKEY PRIMARY KEY (BRANCH_ID),
  CONSTRAINT PNY_MD_BRANCH_UNIQUE_BRANCH_CODE UNIQUE (BRANCH_CODE)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE PNY_MD_BRANCH
  OWNER TO apps_system;


CREATE SEQUENCE PNY_MD_BRANCH_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 20;
ALTER TABLE PNY_MD_BRANCH_SEQ
  OWNER TO apps_system;