  CREATE TABLE PNY_PRODUCT_TYPE
(
  PRODUCT_ID	NUMBER NOT NULL,
  PRODUCT_CODE	CHARACTER VARYING(2),
  PRODUCT_NAME	CHARACTER VARYING(50),
  RECORD_STATUS CHARACTER VARYING(1),
  CREATOR_ID CHARACTER VARYING(20) DEFAULT 'SYSTEM'::CHARACTER VARYING,
  CREATED_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
  LAST_USER_ID CHARACTER VARYING(20) DEFAULT 'SYSTEM'::CHARACTER VARYING,
  LAST_UPDATE TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
  CONSTRAINT PNY_PRODUCT_TYPE_PKEY PRIMARY KEY (PRODUCT_ID),
  CONSTRAINT PNY_PRODUCT_TYPE_UNIQUE_PRODUCT_CODE UNIQUE (PRODUCT_CODE)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE PNY_PRODUCT_TYPE
  OWNER TO apps_system;


CREATE SEQUENCE PNY_PRODUCT_TYPE_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 20;
ALTER TABLE PNY_PRODUCT_TYPE_SEQ
  OWNER TO apps_system;