  CREATE TABLE PNY_TX_APPLICATION
(
	APPL_ID	NUMBER NOT NULL,
	ACCEPT_DATE	TIMESTAMP WITHOUT TIME ZONE,
	CLIENT_ID	NUMBER,
	APPL_NO	CHARACTER VARYING(20),
	APPLICANT_NAME	CHARACTER VARYING(50),
	CARD_ID_NO	CHARACTER VARYING(20),
	PRODUCT_TYPE	CHARACTER VARYING(2),
	SURVEY_TYPE	CHARACTER VARYING(2),
	UPLOAD_ID	NUMBER,
	DELIVER_DATE	TIMESTAMP WITHOUT TIME ZONE,
	RECORD_STATUS CHARACTER VARYING(2),
	APPL_STATUS	CHARACTER VARYING(2),
	CREATED_BY CHARACTER VARYING(50) DEFAULT 'SYSTEM'::CHARACTER VARYING,
	CREATED_ON TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
	MODIFIED_BY	CHARACTER VARYING(50) DEFAULT 'SYSTEM'::CHARACTER VARYING,
	MODIFIED_ON	TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
  CONSTRAINT PNY_TX_APPLICATION_PKEY PRIMARY KEY (UPLOAD_ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE PNY_TX_APPLICATION
  OWNER TO apps_system;


CREATE SEQUENCE PNY_TX_APPLICATION_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 20;
ALTER TABLE PNY_TX_APPLICATION_SEQ
  OWNER TO apps_system;
  
 
  

