  CREATE TABLE PNY_TX_UPLOAD
(
	UPLOAD_ID NUMBER NOT NULL,
	UPLOAD_DATE	DATE,
	UPLOAD_FORMAT_ID NUMBER,
	UPLOAD_FILE_NAME CHARACTER VARYING(200),
	UPLOAD_FILE_LOCATION CHARACTER VARYING(200),
	UPLOAD_FILE_HASH CHARACTER VARYING(32),
	PROCESS_STATUS_CODE	CHARACTER VARYING(2),
	UPLOAD_START_ON	TIMESTAMP WITHOUT TIME ZONE,
	UPLOAD_END_ON TIMESTAMP WITHOUT TIME ZONE,
	PROCESS_START_ON TIMESTAMP WITHOUT TIME ZONE,
	PROCESS_END_ON TIMESTAMP WITHOUT TIME ZONE,
	TOTAL_DATA NUMBER,
	PASS_DATA NUMBER,
	FAIL_DATA NUMBER,
	CREATED_BY CHARACTER VARYING(50) DEFAULT 'SYSTEM'::CHARACTER VARYING,
	CREATED_ON TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
	MODIFIED_BY	CHARACTER VARYING(50) DEFAULT 'SYSTEM'::CHARACTER VARYING,
	MODIFIED_ON	TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
	
  CONSTRAINT PNY_TX_UPLOAD_PKEY PRIMARY KEY (UPLOAD_ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE PNY_TX_UPLOAD
  OWNER TO apps_system;


CREATE SEQUENCE PNY_TX_UPLOAD_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 20;
ALTER TABLE PNY_TX_UPLOAD_SEQ
  OWNER TO apps_system;
  
 
  

