  CREATE TABLE PNY_MD_UPLOAD_FIELD
(
	FIELD_ID	NUMBER NOT NULL,
	UPLOAD_FORMAT_ID	NUMBER,
	FIELD_POSITION	NUMBER,
	FIELD_NAME	CHARACTER VARYING(50),
	FIELD_DESC	CHARACTER VARYING(200),
	FIELD_TYPE	CHARACTER VARYING(50),
	DESTINATION_COLUMN	CHARACTER VARYING(50),
	VAL_IS_REQUIRED	CHARACTER VARYING(1),
	VAL_MIN_LENGTH	NUMBER,
	VAL_MAX_LENGTH	NUMBER,
	VAL_MIN_NUMBER	FLOAT,
	VAL_MAX_NUMBER	FLOAT,
  CONSTRAINT PNY_MD_UPLOAD_FIELD_PKEY PRIMARY KEY (FIELD_ID)
  
  
)
WITH (
  OIDS=FALSE
);
ALTER TABLE PNY_MD_UPLOAD_FIELD
  OWNER TO apps_system;


CREATE SEQUENCE PNY_MD_UPLOAD_FIELD_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 20;
ALTER TABLE PNY_MD_UPLOAD_FIELD_SEQ
  OWNER TO apps_system;
  

