  CREATE TABLE PNY_MD_CLIENT
(
  CLIENT_ID NUMERIC NOT ,
  CLIENT_CODE CHARACTER VARYING(10),
  CLIENT_NAME CHARACTER VARYING(50),
  EMAIL CHARACTER VARYING(50),
  RECORD_STATUS CHARACTER VARYING(1),
  CREATED_BY CHARACTER VARYING(20) DEFAULT 'SYSTEM'::CHARACTER VARYING,
  CREATED_ON TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
  MODIFIED_BY CHARACTER VARYING(20) DEFAULT 'SYSTEM'::CHARACTER VARYING,
  MODIFIED_ON TIMESTAMP WITHOUT TIME ZONE DEFAULT SYSDATE,
  CONSTRAINT PNY_MD_CLIENT_PKEY PRIMARY KEY (CLIENT_ID),
  CONSTRAINT PNY_MD_CLIENT_UNIQUE_CLIENT_CODE UNIQUE (CLIENT_CODE)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE PNY_MD_CLIENT
  OWNER TO apps_system;


CREATE SEQUENCE PNY_MD_CLIENT_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999999
  START 1
  CACHE 20;
ALTER TABLE PNY_MD_CLIENT_SEQ
  OWNER TO apps_system;
  

